services:
  sady-celmerow:
    build: .
    container_name: sady-celmerow
    ports:
      - '3003:3000'
    restart: unless-stopped
    env_file:
      - path: .env.local
        required: false
    environment:
      - NODE_ENV=production
